name: Auto Tasks

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * *'

jobs:
  run:
    runs-on: ubuntu-22.04
    env:
      SENDKEY: ${{ secrets.SENDKEY }}
      RAINYUN_USERNAME: ${{ secrets.RAINYUN_USERNAME }}
      RAINYUN_PASSWORD: ${{ secrets.RAINYUN_PASSWORD }}
      IKUUU_USERNAME: ${{ secrets.IKUUU_USERNAME }}
      IKUUU_PASSWORD: ${{ secrets.IKUUU_PASSWORD }}
      LES_USERNAME: ${{ secrets.LES_USERNAME }}
      LES_PASSWORD: ${{ secrets.LES_PASSWORD }}
      LEAFLOW_COOKIE: ${{ secrets.LEAFLOW_COOKIE }}
      DP_HEADLESS: 1
      DISPLAY: :99
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chromium and dependencies (apt)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            chromium-browser \
            chromium-codecs-ffmpeg-extra \
            fonts-liberation \
            libnss3 libxss1 libgtk-3-0 libxkbcommon0 libgbm1 \
            libasound2 libatk-bridge2.0-0 libdrm2 libxdamage1 libxfixes3 \
            libxcomposite1 libxcursor1 libxi6 libxtst6 libglib2.0-0 \
            xvfb
          which chromium || which chromium-browser || true
          echo "CHROME_BIN=$(which chromium || which chromium-browser)" >> $GITHUB_ENV

      - name: Fallback install Chromium (snap) if missing
        if: env.CHROME_BIN == ''
        run: |
          sudo snap install chromium --classic || true
          echo "CHROME_BIN=$(which chromium || which chromium-browser || echo /snap/bin/chromium)" >> $GITHUB_ENV

      - name: Export DrissionPage browser path
        run: |
          echo "DP_BROWSER_PATH=${CHROME_BIN}" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare Xvfb (headless display)
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          # 等待 Xvfb 启动
          sleep 3

      - name: Run all tasks
        working-directory: ./scripts
        run: |
          python run_all.py

      - name: Upload run logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            **/*.log
            Rainyun/temp/

